### ISSUE TITLE
Add @ operator for dot product

### ISSUE THREAD

**Issue by DavidMertz** [mrocklin/sparse#13]
I have a patch in a branch to implement and add test for `.__matmul__`.  If you can add my permission to write, I'll push it.

**Comment by DavidMertz** [comment]
It's a very small path:

```diff
diff --git a/sparse/core.py b/sparse/core.py
index be9c06c..1c8ee4b 100644
--- a/sparse/core.py
+++ b/sparse/core.py
@@ -328,6 +328,8 @@ class COO(object):
     def dot(self, other):
         return dot(self, other)

+    __matmul__ = dot
+
     def reshape(self, shape):
         if self.shape == shape:
             return self
diff --git a/sparse/tests/test_core.py b/sparse/tests/test_core.py
index e531245..15b44aa 100644
--- a/sparse/tests/test_core.py
+++ b/sparse/tests/test_core.py
@@ -1,5 +1,6 @@
 import pytest

+import sys
 import random
 import operator
 import numpy as np
@@ -136,6 +137,9 @@ def test_dot():
     assert_eq(a.dot(b), sa.dot(sb))
     assert_eq(np.dot(a, b), sparse.dot(sa, sb))

+    if sys.version_info >= (3, 5):
+        assert_eq(a @ b, sa @ sb)
+

 @pytest.mark.parametrize('func', [np.expm1, np.log1p, np.sin, np.tan,
                                    np.sinh,  np.tanh, np.floor, np.ceil

**Comment by jakevdp** [comment]
Hi @DavidMertz – the best way to do this would be to open a [pull request](https://help.github.com/articles/creating-a-pull-request/) — that allows the contribution to be more properly reviewed.

A couple quick comments: it would be worth also implementing ``__rmatmul__``. Also I believe the test you wrote will raise a syntax error for Python versions older than 3.5; you can see how SciPy got around that issue here: https://github.com/scipy/scipy/pull/5347/files

**Comment by DavidMertz** [comment]
I can't do a pull request until I have permission to push to a new branch, no?

**Comment by mrocklin** [comment]
You can fork the repository on github and then submit a PR from your fork.

**Comment by hameerabbasi** [comment]
@DavidMertz Okay to close this?
